export const FETCH_ASSETS = 'FETCH_ASSETS';
export const IS_LOADING = 'IS_LOADING';
export const FETCH_MARKET = 'FETCH_MARKET';
export const FETCH_MARKET_HISTORY_ERROR = 'FETCH_MARKET_HISTORY_ERROR';
